### ISSUE TITLE
[BUG] mysql not working

### ISSUE THREAD

**Issue by mitchngwen** [Lorenzo0111/RocketPlaceholders#110]
mysql does not work.

[23:37:40] [Server thread/INFO]: [RocketPlaceholders] Enabling RocketPlaceholders v2.3
[23:37:40] [Server thread/INFO]: [RocketPlaceholders] Loaded 16 placeholders!
[23:37:40] [Server thread/INFO]: [RocketPlaceholders] MySQL driver is not installed, please install it to use the mysql function
[23:37:40] [Server thread/INFO]: [RocketPlaceholders] Adding placeholders to the database..
[23:37:40] [Server thread/ERROR]: Error occurred while enabling RocketPlaceholders v2.3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.lorenzo0111.rocketplaceholders.lib.mystral.database.AsyncDatabase.update(String, boolean)" because "this.database" is null
	at me.lorenzo0111.rocketplaceholders.database.DatabaseManager.removeAll(DatabaseManager.java:302) ~[RocketPlaceholders-2.3.jar:?]
	at me.lorenzo0111.rocketplaceholders.utilities.PluginLoader.loadDatabase(PluginLoader.java:117) ~[RocketPlaceholders-2.3.jar:?]
	at me.lorenzo0111.rocketplaceholders.RocketPlaceholders.onEnable(RocketPlaceholders.java:121) ~[RocketPlaceholders-2.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:37:40] [Server thread/INFO]: [RocketPlaceholders] Disabling RocketPlaceholders v2.3
[23:37:40] [Server thread/INFO]: [RocketPlaceholders] Plugin disabled! Thanks for using RocketPlaceholders v.2.3

**Comment by Lorenzo0111** [comment]
The database connection is invalid.

**Comment by Iwitrag** [comment]
I have exactly the same problem and the DB info are correctly defined in the config and works in other plugins.
Running 8.0.34 - MySQL Community Server - GPL

**Comment by Lorenzo0111** [comment]
Please try with [this](https://ci.codemc.io/job/Lorenzo0111/job/RocketPlaceholders/lastSuccessfulBuild/artifact/build/libs/RocketPlaceholders-2.3.jar) build.
